apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-rule
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
    - name: nginx-prometheus-rules
      rules:
        - alert: NginxDown
          expr: nginx_up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Nginx está fora"
            description: "O nosso servidor web nginx esta fora!"
        - alert: NginxHighRequestRate
          expr: rate(nginx_http_requests_total[5m]) > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Alta taxa de requisições no Nginx"
            description: "O servidor web nginx está recebendo uma alta taxa de requisições!"