apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # no container ele vai jogar nesse /
spec:
  ingressClassName: nginx
  rules:
  - host: giropops-senhas.local # colocar no /etc/hosts(windows) para resolver esse dominio "127.0.0.1 giropops-senhas.local"
    http:
      paths:
      - path: / # caminho que vai ser acessado externamente
        pathType: Prefix
        backend:
          service:
            name: giropops-senhas
            port:
              number: 5000